### ISSUE TITLE
Chebysehv and Fourier not working after installation

### ISSUE THREAD

**Issue by subhk** [spectralDNS/shenfun#32]
Hi,

  I have started using shenfun. I installed the code using pip. I am trying to test some of the code given in the demo section. It seems to me that the Fourier and Chebyshev not working after the installation. Following things, I did on the Linux(Ubuntu) terminal. I am using python-3.6.

>> from shenfun import Basis
>> F0 = Basis(16, 'F')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aditya0006/.local/lib/python3.6/site-packages/shenfun/forms/arguments.py", line 84, in Basis
    return B(N, **par)
  File "/home/aditya0006/.local/lib/python3.6/site-packages/shenfun/fourier/bases.py", line 332, in __init__
    self.plan((int(padding_factor*N),), (0,), np.float, {})
  File "/home/aditya0006/.local/lib/python3.6/site-packages/shenfun/fourier/bases.py", line 277, in plan
    xfftn_fwd = plan_fwd(U, s=s, axes=axis, threads=threads, flags=flags)
  File "/home/aditya0006/.local/lib/python3.6/site-packages/mpi4py_fft/fftw/xfftn.py", line 240, in rfftn
    flags, 1.0/M)
  File "/home/aditya0006/.local/lib/python3.6/site-packages/mpi4py_fft/fftw/factory.py", line 102, in get_planned_FFT
    assert dtype.upper() in fftlib
AssertionError

I tried a fresh install. The error is repeating.

Any help would be really great.

Thanks
Subhajit

**Comment by mikaem** [comment]
Hi Subhajt

An unfortunate thing with pip is that it does not take care of all [dependencies](https://shenfun.readthedocs.io/en/latest/installation.html), and I think perhaps you are missing MPI/mpi4py? Can you do 

`import mpi4py`

to check if it is there. If not I really recommend installing through Conda instead, or else you need to install the missing dependencies by hand.

**Comment by subhk** [comment]
Thanks, Mikael. Now I did with conda. It is working.

**Comment by mikaem** [comment]
Closing since there's no issue, just pip not installing all dependencies.
