### ISSUE TITLE
2D example crashes with error

### ISSUE THREAD

**Issue by yesint** [spectralDNS/shenfun#34]
When trying to run the dirichlet_poisson2D.py the following error appears:

```
$ python3 dirichlet_poisson2D.py 64 legendre
Traceback (most recent call last):
  File "dirichlet_poisson2D.py", line 49, in <module>
    K1 = Basis(N[1], family='F', dtype='d', domain=(-2*np.pi, 2*np.pi))
  File "/home/syesylev/.local/lib/python3.6/site-packages/shenfun/forms/arguments.py", line 84, in Basis
    return B(N, **par)
  File "/home/syesylev/.local/lib/python3.6/site-packages/shenfun/fourier/bases.py", line 332, in __init__
    self.plan((int(padding_factor*N),), (0,), np.float, {})
  File "/home/syesylev/.local/lib/python3.6/site-packages/shenfun/fourier/bases.py", line 277, in plan
    xfftn_fwd = plan_fwd(U, s=s, axes=axis, threads=threads, flags=flags)
  File "/home/syesylev/.local/lib/python3.6/site-packages/mpi4py_fft/fftw/xfftn.py", line 240, in rfftn
    flags, 1.0/M)
  File "/home/syesylev/.local/lib/python3.6/site-packages/mpi4py_fft/fftw/factory.py", line 102, in get_planned_FFT
    assert dtype.upper() in fftlib
AssertionError
```

An example file is not modified what is the problem?

**Comment by mikaem** [comment]
Hi,

This looks like a problem with the installation of the FFTW wrapper. How did you install shenfun?

**Comment by yesint** [comment]
Hi, I've installed it with pip on Ubuntu based system. fftw3 was preinstalled on the system from standard Ubuntu repository (libfftw3-dev package).

**Comment by mikaem** [comment]
Ok. But it looks like that fftw library was not found. I recommend using conda, because it takes care of all dependencies, otherwise I suggest you clone or fork mpi4py-fft and then install it yourself making sure fftw is found.

**Comment by yesint** [comment]
I reinstalled everything but it still does not work. mpi4py-fft is collected by pip with no problems as you can see below:

```
$ pip3 install --user shenfun
Collecting shenfun
Collecting mpi4py-fft (from shenfun)
Collecting mpi4py (from shenfun)
Collecting numpy (from shenfun)
  Using cached https://files.pythonhosted.org/packages/62/20/4d43e141b5bc426ba38274933ef8e76e85c7adea2c321ecf9ebf7421cedf/numpy-1.18.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting cython (from shenfun)
  Using cached https://files.pythonhosted.org/packages/d1/54/9d66ee2180776dfe33c2b8cc2f2b67c343fd9d80de91ac0edc5bc346fb06/Cython-0.29.15-cp36-cp36m-manylinux1_x86_64.whl
Collecting scipy (from shenfun)
  Using cached https://files.pythonhosted.org/packages/dc/29/162476fd44203116e7980cfbd9352eef9db37c49445d1fec35509022f6aa/scipy-1.4.1-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: numpy, mpi4py, mpi4py-fft, cython, scipy, shenfun
Successfully installed cython-0.29.15 mpi4py-3.0.3 mpi4py-fft-2.0.3 numpy-1.18.1 scipy-1.4.1 shenfun-2.1.0
```
Do you thinks it's a bug in pip which installs broken fftw wrapper?

**Comment by yesint** [comment]
Installing of mpi4py-fft manually also does not help - the same error.

**Comment by mikaem** [comment]
Hi
I don't think it's a bug. It is FFTW not being picked up and it could be something not accounted for in the setup.py of mpi4py-fft. It's a bit weird, because you should get an error message if FFTW is not picked up. To try it out I just installed everything with pip using an ubuntu 18.04 docker-container. I tried to install first with mpich from apt-get, and the rest from pip3. With incomplete FFTW (not the dev) it gives me an error

> Collecting mpi4py-fft (from shenfun)
  Using cached https://files.pythonhosted.org/packages/d4/59/5079ab912dbc67d348e4702c2fdd28226cc7cf32687ae3212557057715b5/mpi4py-fft-2.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5u3locw3/mpi4py-fft/setup.py", line 126, in <module>
        fftw_libs = get_fftw_libs()
      File "/tmp/pip-build-5u3locw3/mpi4py-fft/setup.py", line 73, in get_fftw_libs
        assert len(libs) > 0, "No FFTW libraries found in {}".format(library_dirs)
    AssertionError: No FFTW libraries found in ['/usr/lib/x86_64-linux-gnu', '/usr/lib']

 Adding libfftw3-dev it installs just fine and the example and the rest are ok. So I'm not sure why you don't pick up the FFTW libraries or why you don't get any error messages. What it the output if you clone mpi4py-fft and then run `python setup.py build_ext -i` to build it in-place?

**Comment by yesint** [comment]
Here is the output:
```
~/install/mpi4py-fft$ sudo python3 setup.py build_ext -i
running build_ext
skipping '/home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/utilities.c' Cython extension (up-to-date)
skipping '/home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftwf_xfftn.c' Cython extension (up-to-date)
skipping '/home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftw_xfftn.c' Cython extension (up-to-date)
skipping '/home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftwl_xfftn.c' Cython extension (up-to-date)
copying build/lib.linux-x86_64-3.6/mpi4py_fft/fftw/utilities.cpython-36m-x86_64-linux-gnu.so -> mpi4py_fft/fftw
copying build/lib.linux-x86_64-3.6/mpi4py_fft/fftw/fftwf_xfftn.cpython-36m-x86_64-linux-gnu.so -> mpi4py_fft/fftw
copying build/lib.linux-x86_64-3.6/mpi4py_fft/fftw/fftw_xfftn.cpython-36m-x86_64-linux-gnu.so -> mpi4py_fft/fftw
copying build/lib.linux-x86_64-3.6/mpi4py_fft/fftw/fftwl_xfftn.cpython-36m-x86_64-linux-gnu.so -> mpi4py_fft/fftw
(base) syesylev@opx-9020-P12:~/install/mpi4py-fft$
```

**Comment by mikaem** [comment]
Can you clean the build first? `python3 setup.py clean` and then `python3 setup.py build_ext -i`

**Comment by yesint** [comment]
Here is it. No errors.

```
$ sudo python3 setup.py clean
running clean
removing 'build/temp.linux-x86_64-3.6' (and everything under it)

$ python3 setup.py build_ext -i
running build_ext
cythoning /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/utilities.pyx to /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/utilities.c
cythoning /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftwf_xfftn.pyx to /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftwf_xfftn.c
/home/syesylev/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftwf_xfftn.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)
cythoning /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftw_xfftn.pyx to /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftw_xfftn.c
/home/syesylev/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftw_xfftn.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)
cythoning /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftwl_xfftn.pyx to /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftwl_xfftn.c
/home/syesylev/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftwl_xfftn.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)
building 'mpi4py_fft.fftw.utilities' extension
creating build/temp.linux-x86_64-3.6
error: could not create 'build/temp.linux-x86_64-3.6': Permission denied
syesylev@opx-9020-P12:~/install/mpi4py-fft$ 
syesylev@opx-9020-P12:~/install/mpi4py-fft$ 
syesylev@opx-9020-P12:~/install/mpi4py-fft$ sudo python3 setup.py clean
running clean
syesylev@opx-9020-P12:~/install/mpi4py-fft$ sudo python3 setup.py build_ext -i
running build_ext
cythoning /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/utilities.pyx to /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/utilities.c
cythoning /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftwf_xfftn.pyx to /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftwf_xfftn.c
/home/syesylev/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftwf_xfftn.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)
cythoning /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftw_xfftn.pyx to /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftw_xfftn.c
/home/syesylev/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftw_xfftn.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)
cythoning /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftwl_xfftn.pyx to /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftwl_xfftn.c
/home/syesylev/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftwl_xfftn.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)
building 'mpi4py_fft.fftw.utilities' extension
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/home
creating build/temp.linux-x86_64-3.6/home/syesylev
creating build/temp.linux-x86_64-3.6/home/syesylev/install
creating build/temp.linux-x86_64-3.6/home/syesylev/install/mpi4py-fft
creating build/temp.linux-x86_64-3.6/home/syesylev/install/mpi4py-fft/mpi4py_fft
creating build/temp.linux-x86_64-3.6/home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/x86_64-linux-gnu -I/usr/include -I/home/syesylev/.local/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -c /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/utilities.c -o build/temp.linux-x86_64-3.6/home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/utilities.o
In file included from /home/syesylev/.local/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1832:0,
                 from /home/syesylev/.local/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/syesylev/.local/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/utilities.c:598:
/home/syesylev/.local/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/utilities.o -o build/lib.linux-x86_64-3.6/mpi4py_fft/fftw/utilities.cpython-36m-x86_64-linux-gnu.so
building 'mpi4py_fft.fftw.fftwf_xfftn' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/x86_64-linux-gnu -I/usr/include -I/home/syesylev/.local/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -c /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftwf_xfftn.c -o build/temp.linux-x86_64-3.6/home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftwf_xfftn.o
In file included from /home/syesylev/.local/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1832:0,
                 from /home/syesylev/.local/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/syesylev/.local/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftwf_xfftn.c:600:
/home/syesylev/.local/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/x86_64-linux-gnu -I/usr/include -I/home/syesylev/.local/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -c /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftwf_planxfftn.c -o build/temp.linux-x86_64-3.6/home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftwf_planxfftn.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftwf_xfftn.o build/temp.linux-x86_64-3.6/home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftwf_planxfftn.o -lfftw3f -lfftw3f_threads -lm -o build/lib.linux-x86_64-3.6/mpi4py_fft/fftw/fftwf_xfftn.cpython-36m-x86_64-linux-gnu.so
building 'mpi4py_fft.fftw.fftw_xfftn' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/x86_64-linux-gnu -I/usr/include -I/home/syesylev/.local/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -c /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftw_xfftn.c -o build/temp.linux-x86_64-3.6/home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftw_xfftn.o
In file included from /home/syesylev/.local/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1832:0,
                 from /home/syesylev/.local/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/syesylev/.local/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftw_xfftn.c:600:
/home/syesylev/.local/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/x86_64-linux-gnu -I/usr/include -I/home/syesylev/.local/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -c /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftw_planxfftn.c -o build/temp.linux-x86_64-3.6/home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftw_planxfftn.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftw_xfftn.o build/temp.linux-x86_64-3.6/home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftw_planxfftn.o -lfftw3 -lfftw3_threads -lm -o build/lib.linux-x86_64-3.6/mpi4py_fft/fftw/fftw_xfftn.cpython-36m-x86_64-linux-gnu.so
building 'mpi4py_fft.fftw.fftwl_xfftn' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/x86_64-linux-gnu -I/usr/include -I/home/syesylev/.local/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -c /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftwl_xfftn.c -o build/temp.linux-x86_64-3.6/home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftwl_xfftn.o
In file included from /home/syesylev/.local/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1832:0,
                 from /home/syesylev/.local/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/syesylev/.local/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftwl_xfftn.c:600:
/home/syesylev/.local/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/x86_64-linux-gnu -I/usr/include -I/home/syesylev/.local/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -c /home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftwl_planxfftn.c -o build/temp.linux-x86_64-3.6/home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftwl_planxfftn.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftwl_xfftn.o build/temp.linux-x86_64-3.6/home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/fftwl_planxfftn.o -lfftw3l -lfftw3l_threads -lm -o build/lib.linux-x86_64-3.6/mpi4py_fft/fftw/fftwl_xfftn.cpython-36m-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.6/mpi4py_fft/fftw/utilities.cpython-36m-x86_64-linux-gnu.so -> mpi4py_fft/fftw
copying build/lib.linux-x86_64-3.6/mpi4py_fft/fftw/fftwf_xfftn.cpython-36m-x86_64-linux-gnu.so -> mpi4py_fft/fftw
copying build/lib.linux-x86_64-3.6/mpi4py_fft/fftw/fftw_xfftn.cpython-36m-x86_64-linux-gnu.so -> mpi4py_fft/fftw
copying build/lib.linux-x86_64-3.6/mpi4py_fft/fftw/fftwl_xfftn.cpython-36m-x86_64-linux-gnu.so -> mpi4py_fft/fftw

```

**Comment by mikaem** [comment]
Looks like it builds just fine and finds everything it needs. Now are you sure this local build is the one picked up by shenfun? Are you adding `/home/syesylev/install/mpi4py-fft/` to the PYTHONPATH?

    export PYTHONPATH=/home/syesylev/install/mpi4py-fft/:$PYTHONPATH

**Comment by yesint** [comment]
I installed it systemwide, but just to check:

```
$ export PYTHONPATH=/home/syesylev/install/mpi4py-fft/:$PYTHONPATH
$ python3 dirichlet_poisson2D.py 64 legendre
Traceback (most recent call last):
  File "dirichlet_poisson2D.py", line 49, in <module>
    K1 = Basis(N[1], family='F', dtype='d', domain=(-2*np.pi, 2*np.pi))
  File "/home/syesylev/.local/lib/python3.6/site-packages/shenfun/forms/arguments.py", line 84, in Basis
    return B(N, **par)
  File "/home/syesylev/.local/lib/python3.6/site-packages/shenfun/fourier/bases.py", line 332, in __init__
    self.plan((int(padding_factor*N),), (0,), np.float, {})
  File "/home/syesylev/.local/lib/python3.6/site-packages/shenfun/fourier/bases.py", line 277, in plan
    xfftn_fwd = plan_fwd(U, s=s, axes=axis, threads=threads, flags=flags)
  File "/home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/xfftn.py", line 240, in rfftn
    flags, 1.0/M)
  File "/home/syesylev/install/mpi4py-fft/mpi4py_fft/fftw/factory.py", line 104, in get_planned_FFT
    assert dtype.upper() in fftlib
AssertionError
syesylev@opx-9020-P12:~/work/Projects/SquaMem/new_bending/cyl_dopc$ $PYTHONPATH 
bash: /home/syesylev/install/mpi4py-fft/::/home/syesylev/programs/pteros/python:/home/syesylev/programs/pteros/python: No such file or directory

```
As you can see it uses the path /home/syesylev/install/mpi4py-fft/ but still crashes.

Btw, installation from conda doesn't work for me. It it stuck downloading packages. I killet it after 3 hours (!) at 9%

**Comment by mikaem** [comment]
Still no wiser. Can you do `from mpi4py_fft.fftw import fftw_xfftn`?

**Comment by yesint** [comment]
```
In [1]: from mpi4py_fft.fftw import fftw_xfftn
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-5178e9ea832e> in <module>()
----> 1 from mpi4py_fft.fftw import fftw_xfftn

ImportError: /usr/lib/x86_64-linux-gnu/libfftw3_threads.so.3: undefined symbol: fftw_set_planner_hooks

```

Finally some error! However, I have no clue what does it mean.

**Comment by mikaem** [comment]
Yes, it's no error with the installation, it's an error with the FFTW library! And we're not the first to see it: https://github.com/amirgholami/accfft/issues/11

**Comment by yesint** [comment]
Ups...
So what is the simplest way to fix it? I don't quite understand where exactly should I change the order of the libs? Is it in mpi4py_fft?

**Comment by mikaem** [comment]
Yes, you can change the order in setup.py, line 71. Instead of append use prepend, something like `libs[d].insert(0, tlib)`. Try it!

**Comment by yesint** [comment]
I cleaned the build and made install again. No luck :(  The same error.

ImportError: /usr/lib/x86_64-linux-gnu/libfftw3_threads.so.3: undefined symbol: fftw_set_planner_hooks

**Comment by yesint** [comment]
This is quite nasty bug because it happens on the most mainstream linux distro.

**Comment by mikaem** [comment]
Yes, but I cannot reproduce it in a clean docker ubuntu 18.04 container. So it could be something only happening on your machine? Not sure. Would be easier if I could reproduce:-( Also, noone else has seen this before, and that's kind of strange if it happens on the most mainstream linux distro.

**Comment by yesint** [comment]
Sure, you are completely right ```
and this also drives me crazy. Here is my system:

$ cat /etc/os-release
NAME="Linux Mint"
VERSION="19.3 (Tricia)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19.3"
VERSION_ID="19.3"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.ubuntu.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=tricia
UBUNTU_CODENAME=bionic
```

All the base is Ubuntu bionic, so I have absolutely no clue what is so wrong with it. I'll try on the other machine running the same distro later and let you know.

**Comment by yesint** [comment]
I confirm that this is a problem of one particular machine running Mint 19.3. There is no such problem on the laptop running the same distro. The problem narrows down to the behavior of fftw3 on particular machine. I'd be grateful for any suggestions how can I investigate more.

**Comment by mikaem** [comment]
I think you simply need to install a different version of FFTW...

**Comment by yesint** [comment]
I've finally found the problem! It's very stupid but very hard to debug. There is an Amber14 software installed which comes with its own bundled fftw3 and the LD_LIBRARY_PATH is modified to include it. That is why linking was done with the wrong library.
@mikaem thank you very much for your help and patience :) shenfun is a great piece of software.
