### ISSUE TITLE
tests fail with cython optimization

### ISSUE THREAD

**Issue by francispoulin** [spectralDNS/shenfun#39]
I can happily say that all the tests pass without any optimization.  Today I tried with cython and numba.

The good news is that with numba they all pass.

The bad news is that with cython I have 202 fail.  This is both on my laptop and a computer cluster, but both are installed using conda so it's really the same system.

I will continue to use numba but wanted to point this out, in case you weren't aware of it already.

**Comment by mikaem** [comment]
I did not know. Which tests fail?

**Comment by francispoulin** [comment]
Below is the list that I get.

P.S. Is there a simple way to do bulk indenting in github?
`

    ============================= short test summary info=============================
    FAILED shenfun/tests/test_curl.py::test_curl2 - AssertionError: Use optimized ve...
    FAILED shenfun/tests/test_demos.py::test_demos - subprocess.CalledProcessError: ...
    FAILED shenfun/tests/test_matrices.py::test_helmholtz3D[chebyshev-0] - NotImplem...
    FAILED shenfun/tests/test_matrices.py::test_helmholtz3D[chebyshev-1] - NotImplem...
    FAILED shenfun/tests/test_matrices.py::test_helmholtz3D[chebyshev-2] - NotImplem...
    FAILED shenfun/tests/test_matrices.py::test_helmholtz3D[legendre-0] - AssertionE...
    FAILED shenfun/tests/test_matrices.py::test_helmholtz3D[legendre-1] - AssertionE...
    FAILED shenfun/tests/test_matrices.py::test_helmholtz3D[legendre-2] - AssertionE...
    FAILED shenfun/tests/test_matrices.py::test_helmholtz3D[jacobi-0] - AssertionErr...
    FAILED shenfun/tests/test_matrices.py::test_helmholtz3D[jacobi-1] - AssertionErr...
    FAILED shenfun/tests/test_matrices.py::test_helmholtz3D[jacobi-2] - AssertionErr... 
    FAILED shenfun/tests/test_matrices.py::test_helmholtz2D[chebyshev-0] - NotImplem...
    FAILED shenfun/tests/test_matrices.py::test_helmholtz2D[chebyshev-1] - NotImplem...
    FAILED shenfun/tests/test_matrices.py::test_helmholtz2D[legendre-0] - AssertionE...  
    FAILED shenfun/tests/test_matrices.py::test_helmholtz2D[legendre-1] - AssertionE...
    FAILED shenfun/tests/test_matrices.py::test_helmholtz2D[jacobi-0] - AssertionErr...
    FAILED shenfun/tests/test_matrices.py::test_helmholtz2D[jacobi-1] - AssertionErr...
    FAILED shenfun/tests/test_matrices.py::test_biharmonic3D[chebyshev-0] - NotImple...
    FAILED shenfun/tests/test_matrices.py::test_biharmonic3D[chebyshev-1] - NotImple...
    FAILED shenfun/tests/test_matrices.py::test_biharmonic3D[chebyshev-2] - NotImple...
    FAILED shenfun/tests/test_matrices.py::test_biharmonic3D[legendre-0] - NotImplem...
    FAILED shenfun/tests/test_matrices.py::test_biharmonic3D[legendre-1] - NotImplem...
    FAILED shenfun/tests/test_matrices.py::test_biharmonic3D[legendre-2] - NotImplem...
    FAILED shenfun/tests/test_matrices.py::test_biharmonic3D[jacobi-0] - NotImplemen...
    FAILED shenfun/tests/test_matrices.py::test_biharmonic3D[jacobi-1] - NotImplemen...
    FAILED shenfun/tests/test_matrices.py::test_biharmonic3D[jacobi-2] - NotImplemen...
    FAILED shenfun/tests/test_matrices.py::test_biharmonic2D[chebyshev-0] - NotImple...
    FAILED shenfun/tests/test_matrices.py::test_biharmonic2D[chebyshev-1] - NotImple...
    FAILED shenfun/tests/test_matrices.py::test_biharmonic2D[legendre-0] - NotImplem...
    FAILED shenfun/tests/test_matrices.py::test_biharmonic2D[legendre-1] - NotImplem...
    FAILED shenfun/tests/test_matrices.py::test_biharmonic2D[jacobi-0] - NotImplemen...
    FAILED shenfun/tests/test_matrices.py::test_biharmonic2D[jacobi-1] - NotImplemen...
    FAILED shenfun/tests/test_tensorproductspace.py::test_shentransform[ShenDirichletBasis-LG0-1-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_shentransform[ShenDirichletBasis-LG0-1-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_shentransform[ShenDirichletBasis-LG0-2-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_shentransform[ShenDirichletBasis-LG0-2-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_shentransform[ShenDirichletBasis-GL0-1-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_shentransform[ShenDirichletBasis-GL0-1-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_shentransform[ShenDirichletBasis-GL0-2-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_shentransform[ShenDirichletBasis-GL0-2-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_shentransform[ShenDirichletBasis-GC-1-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_shentransform[ShenDirichletBasis-GC-1-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_shentransform[ShenDirichletBasis-GC-2-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_shentransform[ShenDirichletBasis-GC-2-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_shentransform[ShenDirichletBasis-GL1-1-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_shentransform[ShenDirichletBasis-GL1-1-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_shentransform[ShenDirichletBasis-GL1-2-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_shentransform[ShenDirichletBasis-GL1-2-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_shentransform[ShenNeumannBasis-GC-1-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_shentransform[ShenNeumannBasis-GC-1-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_shentransform[ShenNeumannBasis-GC-2-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_shentransform[ShenNeumannBasis-GC-2-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_shentransform[ShenNeumannBasis-GL1-1-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_shentransform[ShenNeumannBasis-GL1-1-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_shentransform[ShenNeumannBasis-GL1-2-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_shentransform[ShenNeumannBasis-GL1-2-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_shentransform[ShenDirichletBasis-LG1-1-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_shentransform[ShenDirichletBasis-LG1-1-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_shentransform[ShenDirichletBasis-LG1-2-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_shentransform[ShenDirichletBasis-LG1-2-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_shentransform[ShenDirichletBasis-JG-1-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_shentransform[ShenDirichletBasis-JG-1-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_shentransform[ShenDirichletBasis-JG-2-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_shentransform[ShenDirichletBasis-JG-2-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_project[ShenDirichletBasis-LG-1-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_project[ShenDirichletBasis-LG-1-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_project[ShenDirichletBasis-LG-2-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_project[ShenDirichletBasis-LG-2-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_project[ShenDirichletBasis-GL0-1-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_project[ShenDirichletBasis-GL0-1-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_project[ShenDirichletBasis-GL0-2-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_project[ShenDirichletBasis-GL0-2-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_project[ShenDirichletBasis-GC-1-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_project[ShenDirichletBasis-GC-1-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_project[ShenDirichletBasis-GC-2-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_project[ShenDirichletBasis-GC-2-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_project[ShenDirichletBasis-GL1-1-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_project[ShenDirichletBasis-GL1-1-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_project[ShenDirichletBasis-GL1-2-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_project[ShenDirichletBasis-GL1-2-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_project_lag[ShenDirichletBasis-LG-1-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_project_lag[ShenDirichletBasis-LG-1-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_project_lag[ShenDirichletBasis-LG-2-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_project_lag[ShenDirichletBasis-LG-2-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_project2[ShenNeumannBasis-GC-1-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_project2[ShenNeumannBasis-GC-1-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_project2[ShenNeumannBasis-GC-2-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_project2[ShenNeumannBasis-GC-2-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_project2[ShenNeumannBasis-GL1-1-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_project2[ShenNeumannBasis-GL1-1-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_project2[ShenNeumannBasis-GL1-2-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_project2[ShenNeumannBasis-GL1-2-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_project_2dirichlet[LG] - A...
    FAILED shenfun/tests/test_tensorproductspace.py::test_project_2dirichlet[GL] - A...
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenDirichletBasis-LG-1-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenDirichletBasis-LG-1-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenDirichletBasis-LG-2-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenDirichletBasis-LG-2-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenDirichletBasis-GL0-1-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenDirichletBasis-GL0-1-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenDirichletBasis-GL0-2-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenDirichletBasis-GL0-2-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenBiharmonicBasis-LG-1-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenBiharmonicBasis-LG-1-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenBiharmonicBasis-LG-2-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenBiharmonicBasis-LG-2-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenBiharmonicBasis-GL0-1-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenBiharmonicBasis-GL0-1-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenBiharmonicBasis-GL0-2-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenBiharmonicBasis-GL0-2-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenDirichletBasis-GC-1-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenDirichletBasis-GC-1-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenDirichletBasis-GC-2-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenDirichletBasis-GC-2-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenDirichletBasis-GL1-1-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenDirichletBasis-GL1-1-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenDirichletBasis-GL1-2-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenDirichletBasis-GL1-2-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenNeumannBasis-GC-1-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenNeumannBasis-GC-1-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenNeumannBasis-GC-2-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenNeumannBasis-GC-2-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenNeumannBasis-GL1-1-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenNeumannBasis-GL1-1-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenNeumannBasis-GL1-2-d]
   FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenNeumannBasis-GL1-2-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenBiharmonicBasis-GC-1-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenBiharmonicBasis-GC-1-D]
   FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenBiharmonicBasis-GC-2-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenBiharmonicBasis-GC-2-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenBiharmonicBasis-GL1-1-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenBiharmonicBasis-GL1-1-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenBiharmonicBasis-GL1-2-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenBiharmonicBasis-GL1-2-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenDirichletBasis-JG-1-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenDirichletBasis-JG-1-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenDirichletBasis-JG-2-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenDirichletBasis-JG-2-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenBiharmonicBasis-JG-1-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenBiharmonicBasis-JG-1-D]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenBiharmonicBasis-JG-2-d]
    FAILED shenfun/tests/test_tensorproductspace.py::test_eval_tensor[ShenBiharmonicBasis-JG-2-D]
    FAILED shenfun/tests/test_transforms.py::test_to_ortho[ShenDirichletBasis-LG0]
    FAILED shenfun/tests/test_transforms.py::test_to_ortho[ShenDirichletBasis-LG1]
    FAILED shenfun/tests/test_transforms.py::test_to_ortho[ShenDirichletBasis-GL0]
    FAILED shenfun/tests/test_transforms.py::test_to_ortho[ShenDirichletBasis-GC] - ...
    FAILED shenfun/tests/test_transforms.py::test_to_ortho[ShenDirichletBasis-GL1]
    FAILED shenfun/tests/test_transforms.py::test_to_ortho[ShenNeumannBasis-GC] - As...
    FAILED shenfun/tests/test_transforms.py::test_to_ortho[ShenNeumannBasis-GL1] - A...
    FAILED shenfun/tests/test_transforms.py::test_transforms[2-ShenDirichletBasis-LG0]
    FAILED shenfun/tests/test_transforms.py::test_transforms[2-ShenDirichletBasis-LG1]
    FAILED shenfun/tests/test_transforms.py::test_transforms[2-ShenDirichletBasis-GL0]
    FAILED shenfun/tests/test_transforms.py::test_transforms[2-ShenBiharmonicBasis-LG]
    FAILED shenfun/tests/test_transforms.py::test_transforms[2-ShenBiharmonicBasis-GL0]
    FAILED shenfun/tests/test_transforms.py::test_transforms[2-ShenDirichletBasis-GC]
    FAILED shenfun/tests/test_transforms.py::test_transforms[2-ShenDirichletBasis-GL1]
    FAILED shenfun/tests/test_transforms.py::test_transforms[2-ShenNeumannBasis-GC]
    FAILED shenfun/tests/test_transforms.py::test_transforms[2-ShenNeumannBasis-GL1]
    FAILED shenfun/tests/test_transforms.py::test_transforms[2-ShenBiharmonicBasis-GC]
    FAILED shenfun/tests/test_transforms.py::test_transforms[2-ShenBiharmonicBasis-GL1]
    FAILED shenfun/tests/test_transforms.py::test_transforms[3-ShenDirichletBasis-LG0]
    FAILED shenfun/tests/test_transforms.py::test_transforms[3-ShenDirichletBasis-LG1]
    FAILED shenfun/tests/test_transforms.py::test_transforms[3-ShenDirichletBasis-GL0]
    FAILED shenfun/tests/test_transforms.py::test_transforms[3-ShenBiharmonicBasis-LG]
    FAILED shenfun/tests/test_transforms.py::test_transforms[3-ShenBiharmonicBasis-GL0]
    FAILED shenfun/tests/test_transforms.py::test_transforms[3-ShenDirichletBasis-GC]
    FAILED shenfun/tests/test_transforms.py::test_transforms[3-ShenDirichletBasis-GL1]
    FAILED shenfun/tests/test_transforms.py::test_transforms[3-ShenNeumannBasis-GC]
    FAILED shenfun/tests/test_transforms.py::test_transforms[3-ShenNeumannBasis-GL1]
    FAILED shenfun/tests/test_transforms.py::test_transforms[3-ShenBiharmonicBasis-GC]
    FAILED shenfun/tests/test_transforms.py::test_transforms[3-ShenBiharmonicBasis-GL1]
    FAILED shenfun/tests/test_transforms.py::test_axis[0-ShenDirichletBasis-LG0] - A...
    FAILED shenfun/tests/test_transforms.py::test_axis[0-ShenDirichletBasis-LG1] - A...
    FAILED shenfun/tests/test_transforms.py::test_axis[0-ShenDirichletBasis-GL0] - A...
    FAILED shenfun/tests/test_transforms.py::test_axis[0-ShenDirichletBasis-GC] - As...
    FAILED shenfun/tests/test_transforms.py::test_axis[0-ShenDirichletBasis-GL1] - A...
    FAILED shenfun/tests/test_transforms.py::test_axis[0-ShenNeumannBasis-GC] - Asse...
    FAILED shenfun/tests/test_transforms.py::test_axis[0-ShenNeumannBasis-GL1] - Ass...
    FAILED shenfun/tests/test_transforms.py::test_axis[1-ShenDirichletBasis-LG0] - A...
    FAILED shenfun/tests/test_transforms.py::test_axis[1-ShenDirichletBasis-LG1] - A...
    FAILED shenfun/tests/test_transforms.py::test_axis[1-ShenDirichletBasis-GL0] - A...
    FAILED shenfun/tests/test_transforms.py::test_axis[1-ShenBiharmonicBasis-LG] - a...
    FAILED shenfun/tests/test_transforms.py::test_axis[1-ShenBiharmonicBasis-GL0] - ...
    FAILED shenfun/tests/test_transforms.py::test_axis[1-ShenDirichletBasis-GC] - As...
    FAILED shenfun/tests/test_transforms.py::test_axis[1-ShenDirichletBasis-GL1] - A...
    FAILED shenfun/tests/test_transforms.py::test_axis[1-ShenNeumannBasis-GC] - Asse...
    FAILED shenfun/tests/test_transforms.py::test_axis[1-ShenNeumannBasis-GL1] - Ass...
    FAILED shenfun/tests/test_transforms.py::test_axis[1-ShenBiharmonicBasis-GC] - a...
    FAILED shenfun/tests/test_transforms.py::test_axis[1-ShenBiharmonicBasis-GL1] - ...
    FAILED shenfun/tests/test_transforms.py::test_axis[2-ShenDirichletBasis-LG0] - A...
    FAILED shenfun/tests/test_transforms.py::test_axis[2-ShenDirichletBasis-LG1] - A...
    FAILED shenfun/tests/test_transforms.py::test_axis[2-ShenDirichletBasis-GL0] - A...
    FAILED shenfun/tests/test_transforms.py::test_axis[2-ShenBiharmonicBasis-LG] - a...
    FAILED shenfun/tests/test_transforms.py::test_axis[2-ShenBiharmonicBasis-GL0] - ...
    FAILED shenfun/tests/test_transforms.py::test_axis[2-ShenDirichletBasis-GC] - As...
    FAILED shenfun/tests/test_transforms.py::test_axis[2-ShenDirichletBasis-GL1] - A...
    FAILED shenfun/tests/test_transforms.py::test_axis[2-ShenNeumannBasis-GC] - Asse...
    FAILED shenfun/tests/test_transforms.py::test_axis[2-ShenNeumannBasis-GL1] - Ass...
    FAILED shenfun/tests/test_transforms.py::test_axis[2-ShenBiharmonicBasis-GC] - a...
    FAILED shenfun/tests/test_transforms.py::test_axis[2-ShenBiharmonicBasis-GL1] - ...
    FAILED shenfun/tests/test_transforms.py::test_CDDmat[GC] - AssertionError: Use o...
    FAILED shenfun/tests/test_transforms.py::test_CDDmat[GL] - AssertionError: Use o...
   ============ 202 failed, 6831 passed, 61 warnings in 109.99s (0:01:49) ============
`

**Comment by sebglane** [comment]
Hi,
FYI: I am currently running the tests from the conda package and `test_tensorproductspace.py` fails.

```
python test_tensorproductspace.py
Traceback (most recent call last):
  File "test_tensorproductspace.py", line 707, in <module>
    test_eval_tensor('d', 1, lbases.ShenBiPolar0Basis, 'LG')
  File "test_tensorproductspace.py", line 513, in test_eval_tensor
    result = fft.eval(points, u_hat, method=0)
  File "/home/sg/anaconda3/envs/shenfun/lib/python3.8/site-packages/shenfun/tensorproductspace.py", line 358, in eval
    return self._eval_lm_cython(points, coefficients, output_array)
  File "/home/sg/anaconda3/envs/shenfun/lib/python3.8/site-packages/shenfun/tensorproductspace.py", line 474, in _eval_lm_cython
    output_array = evaluate.evaluate_lm_2D(list(self.bases), output_array, coefficients, x[0], x[1], w[0], w[1], r2c, last_conj_index, sl)
  File "shenfun/optimization/cython/evaluate.pyx", line 540, in shenfun.optimization.cython.evaluate.evaluate_lm_2D
  File "shenfun/optimization/cython/evaluate.pyx", line 644, in shenfun.optimization.cython.evaluate._evaluate_lm_2D_rc1
  File "/home/sg/anaconda3/envs/shenfun/lib/python3.8/site-packages/shenfun/legendre/bases.py", line 1070, in evaluate_basis
    output_array[:] = sympy.lambdify(X, self.sympy_basis(i, X))(x)
  File "/home/sg/anaconda3/envs/shenfun/lib/python3.8/site-packages/shenfun/legendre/bases.py", line 1054, in sympy_basis
    assert i < self.N-3
AssertionError
```
I do know if this error is related to an outdated conda package or if it does not occur if the current github-Version is used.

Best,
Sebastian
